# Generated by Django 6.0 on 2025-12-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_payment_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
