# Generated by Django 6.0 on 2025-12-31 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_visitor_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-31'),
            preserve_default=False,
        ),
    ]
